/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
untracked fun main(): void {
 testAstlower(); 
}

untracked fun testAstlower(): void {
  myFun = Fun{
    name => "foo",
    sig => FunSig(
      Array[Param("x", TInt()), Param("y", TInt())],
      TInt(),
    ),
    body => Some(
      Array[
        Equation(
          LName("x2"),
          EBinop(Mult(), EVar("x"), EVar("x")) 
        ),
        Equation(
          LName("y2"),
          EBinop(Mult(), EVar("y"), EVar("y"))
        ),
        Equation(
          LName("xy"),
          EBinop(Mult(), EVar("x"), EVar("y"))
        ),
        Equation(
          LName("output"),
          EBinop(Plus(), EVar("x2"), EVar("y2"))
        )
      ],
    ),
  };
  llvmContext = lower(myFun);
  print_module(llvmContext);
  release_context(llvmContext);
}
